### ISSUE TITLE
Intermittent SSL handshake problem yo12345

### ISSUE THREAD

**Issue by torarvid** [torarvid/slackirc#1]
Some times, it has issues connecting to an IRC server that uses SSL. I get error messages like these:

```
uncaughtException: 140056810485632:error:1408F10B:SSL
routines:SSL3_GET_RECORD:wrong version
number:../deps/openssl/openssl/ssl/s3_pkt.c:338:  date=Tue Oct 07 2014
14:14:21 GMT+0200 (CEST), pid=1729, uid=1000, gid=1000,
cwd=/home/ubuntu/src/slackirc, execPath=/usr/local/bin/node,
version=v0.10.31, argv=[node, /home/ubuntu/src/slackirc/server.js],
rss=42229760, heapTotal=31127296, heapUsed=19500432, loadavg=[0.21142578125,
0.1640625, 0.06396484375], uptime=124.08976, trace=[column=18, file=tls.js,
function=SlabBuffer.use, line=234, method=use, native=false, column=29,
file=tls.js, function=CleartextStream.read [as _read], line=454, method=read
[as _read], native=false, column=10, file=_stream_readable.js,
function=CleartextStream.Readable.read, line=340, method=Readable.read,
native=false, column=25, file=tls.js, function=EncryptedStream.write [as
_write], line=368, method=write [as _write], native=false, column=10,
file=_stream_writable.js, function=doWrite, line=225, method=null,
native=false, column=5, file=_stream_writable.js, function=writeOrBuffer,
line=215, method=null, native=false, column=11, file=_stream_writable.js,
function=EncryptedStream.Writable.write, line=182, method=Writable.write,
native=false, column=24, file=_stream_readable.js, function=write, line=601,
method=null, native=false, column=7, file=_stream_readable.js,
function=flow, line=610, method=null, native=false, column=5,
file=_stream_readable.js, function=Socket.pipeOnReadable, line=642,
method=pipeOnReadable, native=false], stack=[Error:
140056810485632:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version
number:../deps/openssl/openssl/ssl/s3_pkt.c:338:, , at SlabBuffer.use
(tls.js:234:18), at CleartextStream.read [as _read] (tls.js:454:29), at
CleartextStream.Readable.read (_stream_readable.js:340:10), at
EncryptedStream.write [as _write] (tls.js:368:25), at doWrite
(_stream_writable.js:225:10), at writeOrBuffer (_stream_writable.js:215:5),
at EncryptedStream.Writable.write (_stream_writable.js:182:11), at write
(_stream_readable.js:601:24), at flow (_stream_readable.js:610:7), at
Socket.pipeOnReadable (_stream_readable.js:642:5)]
```

**Comment by torarvid** [comment]
test yo

**Comment by torarvid** [comment]
test tag @ksimons and @aliak00 yo yo

**Comment by torarvid** [comment]
test tag @ksimons and @aliak00 yo yo 2

**Comment by torarvid** [comment]
test tag @ksimons and @aliak00 yo yo 3

**Comment by torarvid** [comment]
test tag @ksimons and @aliak00 yo yo 4
